language: shell
dist: xenial
cache:
  directories:
    - /home/travis/.cache/bazel/
os: linux
services:
  - docker
jobs:
  include:
   - os: linux
     arch: amd64
     env: RUNSC_PATH=./bazel-bin/runsc/linux_amd64_pure_stripped/runsc
   - os: linux
     arch: arm64
     env: RUNSC_PATH=./bazel-bin/runsc/linux_arm64_pure_stripped/runsc
script:
   - uname -a
   - make DOCKER_RUN_OPTIONS="" runsc && $RUNSC_PATH --alsologtostderr --network none --debug --TESTONLY-unsafe-nonroot=true --rootless do ls
branches:
  except:
  # Skip copybara branches.
  - /^test\/cl.*$/
